builds:
  - binary: aoj
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/travelist/aoj-cli/cmd.Version={{.Version}}
      - -X github.com/travelist/aoj-cli/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
archives:
  - replacements:
      darwin: macOS
      linux: Linux
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: aoj
    github:
      owner: travelist
      name: homebrew-aoj-cli
    commit_author:
      name: travelist
      email: komei.t.f@gmail.com
    homepage: "https://github.com/travelist/aoj-cli"
    description: "A command-line tool for Aizu Online Judge (AOJ)"
