builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/travelist/aoj-cli/cmd.Version={{.Version}}
      - -X github.com/travelist/aoj-cli/cmd.Revision={{.ShortCommit}}
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
