package constant

const INVALID_REFRESH_TOKEN_ERROR_ID = 1102
const INVALID_REFRESH_TOKEN_ERROR_CODE = "INVALID_REFRESH_TOKEN_ERROR_CODE"

// Error Code
const RESOURCE_NOT_EXIST_ERROR_ID = 2004
const RESOURCE_NOT_EXIST_ERROR_CODE = "RESOURCE_NOT_EXIST_ERROR"

const INTERNAL_SERVER_ERROR_ID = 4001
const INTERNAL_SERVER_ERROR_CODE = "INTERNAL_SERVER_ERROR:500"
